### ISSUE TITLE
Removing mobilecheck method

### ISSUE THREAD

**Issue by superguigui** [brindille/brindille-interactive-component#3]
I'm thinking about removing [mobilecheck](https://github.com/brindille/brindille-interactive-component/blob/master/src/index.js#L5) function from InteractiveComponent.
It shouldn't be this class concern, the isMobile should be decided by the user of the class. I'm thinking to replace it by a getter setter in the class that will (remove and) add the proper listeners.
By default isMobile will be false and set to true if window.isMobile exists, otherwise it will need to be triggered manually.
This function is hard to maintain and should not be inside this module.

**Comment by LaetitiaNanni** [comment]
You're right. It will be more convenient since with already have the detection on the server side.

**Comment by vdaguenet** [comment]
Done in commit https://github.com/brindille/brindille-interactive-component/commit/6eadf6f65046de0f9e5d3f4b180845c977e83386
